apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    ccm: external
    csi: external
  name: example
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.131.0.0/16
  topology:
    class: cpf-aws-cluster-class
    version: v1.31.0
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
        - class: default-worker
          name: md-0
          replicas: 1
    variables:
      - name: region
        value: ap-northeast-2
      - name: sshKeyName
        value: ec2-keypair
      - name: controlPlaneMachineType
        value: t3.medium
      - name: controlPlaneMachineAmiId
        value: ""
      - name: controlPlaneMachineRootVolume
        value: 0
      - name: controlPlanePublicIP
        value: false
      - name: workerMachineType
        value: t3.medium
      - name: workerMachineAmiId
        value: ""
      - name: workerMachineRootVolume
        value: 0
      - name: workerMachinePublicIP
        value: false
      - name: bastionEnabled
        value: false
      - name: bastionAmiId
        value: ""
      - name: vpcAZUsageLimit
        value: 1
      - name: vpcId
        value: ""
      - name: internetGatewayId
        value: ""
      - name: subnetsIds
        value: []
      - name: securityGroupOverrideControlPlane
        value: ""
      - name: securityGroupOverrideApiserverLB
        value: ""
      - name: securityGroupOverrideNode
        value: ""
      - name: securityGroupOverrideLB
        value: ""
      - name: securityGroupOverrideBastion
        value: ""
